version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: picturethisPHPMYSQL_db
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./picfePHPMYSQL/cpanel-html-mysql-app/setup_database.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

  adminer:
    image: adminer
    container_name: picturethisPHPMYSQL_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  db_data:
