version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: picturethis-postgres
    environment:
      POSTGRES_DB: PictureThis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 200Sti007@
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
